tasks:
  - init: pip3 install -r docs/requirements.txt
  - name: Open workspace on welcome page
    command: gp open .vscode/welcome.md

vscode:
  extensions:
    - lextudio.restructuredtext
    - trond-snekvik.simple-rst
