name: Merge approved PR to development
on:
  workflow_run:
    workflows: ["Check if PR is approved"]
    types:
      - completed
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request_review' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Get approved PR number'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
      - run: unzip pr.zip

      - name: 'Merge to development'
        uses: actions/checkout@v2
        with:
          ref: development
          fetch-depth: 0
          token: ${{ secrets.MAUTIBOT_PAT }}
        run: |
          pr=$(cat './NR')
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin pull/${pr}/head:temp
          git merge --squash --no-edit temp
          git commit -m 'Merged latest from PR ${pr}';
          git push