name: Check if PR is approved
on:
  pull_request_review:
    types: [submitted]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - uses: actions/checkout@v2

      - name: 'Store approved PR'
        run: |
          mkdir -p ./pr
          echo ${{ github.event.pull_request.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/